import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const vazirFont = localFont({src: "../../public/font/Vazirmatn-Regular.woff2" });

export const metadata: Metadata = {
  title: "olive&avery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazirFont.className}>{children}</body>
    </html>
  );
}
