import React from "react";
import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import { CartProvider } from "./context/cartContext";

const vazirFont = localFont({src: "../../public/font/Vazirmatn-Regular.woff2" });

export const metadata: Metadata = {
  title: "olive&avery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={vazirFont.className}>
        <CartProvider>{children}</CartProvider>
        </body>
    </html>
  );
}


